apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-html
  template:
    metadata:
      labels:
        app: index-html
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-files
        configMap:
          name: index-html-config
