apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-config
data:
  index.html: |
    # Paste the content of your index.html file here

---
apiVersion: v1
kind: Service
metadata:
  name: index-html-service
spec:
  selector:
    app: index-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
